/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShoppingIndexRouteImport } from './routes/shopping/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as RecipesIdRouteImport } from './routes/recipes/$id'
import { Route as RecipesIdEditRouteImport } from './routes/recipes_/$id.edit'
import { Route as RecipesIdCookingRouteImport } from './routes/recipes_/$id.cooking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingIndexRoute = ShoppingIndexRouteImport.update({
  id: '/shopping/',
  path: '/shopping/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdEditRoute = RecipesIdEditRouteImport.update({
  id: '/recipes_/$id/edit',
  path: '/recipes/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdCookingRoute = RecipesIdCookingRouteImport.update({
  id: '/recipes_/$id/cooking',
  path: '/recipes/$id/cooking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes/': typeof RecipesIndexRoute
  '/shopping/': typeof ShoppingIndexRoute
  '/recipes/$id/cooking': typeof RecipesIdCookingRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes': typeof RecipesIndexRoute
  '/shopping': typeof ShoppingIndexRoute
  '/recipes/$id/cooking': typeof RecipesIdCookingRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes/': typeof RecipesIndexRoute
  '/shopping/': typeof ShoppingIndexRoute
  '/recipes_/$id/cooking': typeof RecipesIdCookingRoute
  '/recipes_/$id/edit': typeof RecipesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recipes/$id'
    | '/recipes/'
    | '/shopping/'
    | '/recipes/$id/cooking'
    | '/recipes/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recipes/$id'
    | '/recipes'
    | '/shopping'
    | '/recipes/$id/cooking'
    | '/recipes/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/recipes/$id'
    | '/recipes/'
    | '/shopping/'
    | '/recipes_/$id/cooking'
    | '/recipes_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipesIdRoute: typeof RecipesIdRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  ShoppingIndexRoute: typeof ShoppingIndexRoute
  RecipesIdCookingRoute: typeof RecipesIdCookingRoute
  RecipesIdEditRoute: typeof RecipesIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping/': {
      id: '/shopping/'
      path: '/shopping'
      fullPath: '/shopping/'
      preLoaderRoute: typeof ShoppingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes_/$id/edit': {
      id: '/recipes_/$id/edit'
      path: '/recipes/$id/edit'
      fullPath: '/recipes/$id/edit'
      preLoaderRoute: typeof RecipesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes_/$id/cooking': {
      id: '/recipes_/$id/cooking'
      path: '/recipes/$id/cooking'
      fullPath: '/recipes/$id/cooking'
      preLoaderRoute: typeof RecipesIdCookingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipesIdRoute: RecipesIdRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  ShoppingIndexRoute: ShoppingIndexRoute,
  RecipesIdCookingRoute: RecipesIdCookingRoute,
  RecipesIdEditRoute: RecipesIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
